fix = true
line-length = 88
indent-width = 4
exclude = [".git", ".pytest_cache", ".ruff_cache", ".venv"]
output-format = "concise"

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint]
preview = true
select = [
    "D",
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
    "RET",
    "PERF101",
    "PERF102",
    "PERF402",
    "RUF006",
    "RUF008",
    "RUF009",
    "B035",
    "PLE",
    "PLW",
    "NPY",
    "PD",
    "PTH",
    "C4",
    "PLC0131",
    "PLC0205",
    "PLC0206",
    "PLC0208",
    "PLC0414",
    "PLC1802",
    "PLC2801",
    "PLC3002",
    "ASYNC",
    "A",
    "ARG",
    "PIE",
    "ISC001",
    "ISC004",
    "ICN",
    "TID252",
    "N",
]
ignore = ["PLW0108", "N803", "N806", "ARG001", "ARG002", "RUF069", "F401"]

[lint.pydocstyle]
convention = "pep257"

[lint.per-file-ignores]
"**/tests/**" = ["D", "E501", "ARG002", "SIM102", "RUF029"]
"**/migrations/**" = ["D", "E501"]
