fix = true
line-length = 88
indent-width = 4
exclude = [".git", ".pytest_cache", ".ruff_cache", ".venv"]
output-format = "concise"

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint]
preview = true
select = ["E", "W", "F", "I", "B", "C4", "UP", "ARG001", "T201"]
ignore = ["B008", "B904"]

[lint.pydocstyle]
convention = "pep257"

[lint.per-file-ignores]
"**/tests/**" = ["D", "E501", "ARG002", "SIM102", "RUF029"]
"**/migrations/**" = ["D", "E501"]
