[terminal]
output-format = "concise"

[src]
exclude = [
    ".venv",
    "build",
    "dist",
    "docs",
    "examples",
    "mypy_cache",
    "pytest_cache",
    "ruff_cache",
]

[rules]
all = "warn"
