#!/usr/bin/env python3
"""Report slowest pytest tests/files from JUnit XML.

This is meant for CI and local triage:
- Identify slow test cases / files.
- Fail the run if a single test (or file aggregate) exceeds a threshold.

Works with JUnit XML generated by: `python3 -m pytest --junitxml=...`.
"""

from __future__ import annotations

import argparse
import statistics
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class _Testcase:
    name: str
    classname: str | None
    file: str | None
    seconds: float


def _iter_xml_paths(path: Path) -> Iterable[Path]:
    if path.is_dir():
        yield from sorted(p for p in path.rglob("*.xml") if p.is_file())
        return
    yield path


def _safe_float(value: str | None) -> float:
    if value is None:
        return 0.0
    try:
        return float(value)
    except ValueError:
        return 0.0


def _guess_file_from_classname(classname: str) -> str | None:
    # pytest usually sets classname like "tests.test_mod" or
    # "tests.test_mod.TestClass".
    # Prefer full module path up to first class name: keep all but last segment
    # if it looks like a class (starts with uppercase).
    parts = classname.split(".")
    if len(parts) >= 2 and parts[-1][:1].isupper():
        parts = parts[:-1]

    # If it already looks like a path, keep it.
    joined = "/".join(parts)
    if "/" in joined and joined.endswith(".py"):
        return joined

    if not joined:
        return None
    return f"{joined}.py"


def _testcase_id(case: _Testcase) -> str:
    if case.classname:
        return f"{case.classname}::{case.name}"
    return case.name


def _file_id(case: _Testcase) -> str | None:
    if case.file:
        return case.file
    if case.classname:
        return _guess_file_from_classname(case.classname)
    return None


def _parse_junit_xml(xml_path: Path) -> list[_Testcase]:
    try:
        root = ET.parse(xml_path).getroot()
    except (ET.ParseError, OSError) as exc:
        raise RuntimeError(f"Failed to parse {xml_path}: {exc}") from exc

    out: list[_Testcase] = []
    for testcase in root.iter("testcase"):
        name = testcase.get("name") or ""
        classname = testcase.get("classname")
        file_attr = testcase.get("file")
        seconds = _safe_float(testcase.get("time"))
        out.append(
            _Testcase(
                name=name,
                classname=classname,
                file=file_attr,
                seconds=seconds,
            )
        )
    return out


def _print_rows(rows: list[tuple[str, float]], top: int) -> None:
    if not rows:
        print("No test timings found.")
        return

    shown = rows[:top] if top > 0 else rows
    width = max(len(name) for name, _ in shown)
    for name, seconds in shown:
        print(f"{name:<{width}}  {seconds:9.3f}s")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--junitxml",
        required=True,
        type=Path,
        help="JUnit XML file or directory containing XML files.",
    )
    parser.add_argument(
        "--mode",
        choices=("testcase", "file"),
        default="testcase",
        help="Report slowest individual testcases or aggregate by file.",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=20,
        help="Number of rows to print (0 = all).",
    )
    parser.add_argument(
        "--min-seconds",
        type=float,
        default=0.0,
        help="Ignore entries below this duration.",
    )
    parser.add_argument(
        "--fail-over",
        type=float,
        default=None,
        help="Exit non-zero if any entry exceeds this many seconds.",
    )
    args = parser.parse_args(argv)

    xml_paths = list(_iter_xml_paths(args.junitxml))
    if not xml_paths:
        print(f"No XML files found under: {args.junitxml}", file=sys.stderr)
        return 2

    testcases: list[_Testcase] = []
    for xml_path in xml_paths:
        testcases.extend(_parse_junit_xml(xml_path))

    if args.mode == "testcase":
        rows = [
            (_testcase_id(c), c.seconds)
            for c in testcases
            if c.seconds >= args.min_seconds
        ]
    else:
        by_file: dict[str, float] = {}
        for c in testcases:
            file_id = _file_id(c)
            if not file_id:
                continue
            if c.seconds < args.min_seconds:
                continue
            by_file[file_id] = by_file.get(file_id, 0.0) + c.seconds
        rows = list(by_file.items())

    rows.sort(key=lambda r: r[1], reverse=True)
    _print_rows(rows, top=args.top)

    if args.fail_over is not None:
        worst = rows[0][1] if rows else 0.0
        if worst > args.fail_over:
            return 1

    if rows:
        values = [s for _, s in rows]
        p50 = statistics.median(values)
        p95 = statistics.quantiles(values, n=20)[18] if len(values) >= 20 else None
        print("")
        print(f"count={len(values)} p50={p50:.3f}s", end="")
        if p95 is not None:
            print(f" p95~={p95:.3f}s")
        else:
            print("")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
